### ISSUE TITLE
[4pt]  - Display Reservations pop up with selected item's details - Student C

### ISSUE THREAD

**Issue by chelobotix** [chelobotix/Retro-Watchers-Capstone#13]
Create a reservations popup only with the top section (displaying details of the selected item)

<img width="519" alt="Screenshot 2021-06-27 at 22 10 45" src="https://user-images.githubusercontent.com/7466903/123558062-a21eef00-d794-11eb-83c4-f5cbdc83421e.png">

When the popup loads, the webapp retrieves data from the selected API and shows details about the selected item.

Add event to button prepared by your teammate that will open your popup. You need to communicate with your team member to make sure that you do not block each other (most likely the easiest solution is to merge the list of items feature to the dev branch before you try to add that event).

**Comment by joskalenda** [comment]
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @chelobotix and @FevenSeyfu , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media0.giphy.com/media/Od0QRnzwRBYmDU3eEO/giphy.gif"/> |

## Highlights

- [ ]... ✅ Well created the issues

## Required Changes ♻️
_Check the comments under the review._

- [ ] While you have done appreciable work, there are some sections you guys missed to implement, since you are a group of 2 students, the requirement asks that all issues with the `C` flag should be removed, only stay with student A and B.
- [ ] The second one, you did not do is to assign each student to his corresponding issue of your choice, student A maybe @chelobotix  and student B @FevenSeyfu, work on assigning issues tasks and resubmit your work for checking.

<img width="402" alt="1" src="https://user-images.githubusercontent.com/77843050/218596596-edfdc492-6c8a-495b-aa09-2fc9d5b83e69.png">


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by chelobotix** [comment]
Dear @joskalenda You commented on the wrong Issue. The correct issue is [https://github.com/chelobotix/Retro-Watchers-Capstone/issues/21](https://github.com/chelobotix/Retro-Watchers-Capstone/issues/21). I need to removed this Issue because it belongs to the coding partner "C".
Please post your observation on the correct issue, as I can delete this one without problems.
Thanks!

**Comment by chelobotix** [comment]
Dear @joskalenda ,any new?
